# Advanced Array Manipulation
## Reshaping Arrays

In [4]:
import numpy as np
arr = np.arange(8)
arr2 = arr.reshape((4, 2))  # create a view, data not copied
arr3 = arr2.reshape((2, 2, 2))   # create a view
arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
# raveling and flattening
arr3.ravel()  # does not create a copy if the values in the result were contiguous in the original array
arr3.flatten()  # always create a copy

array([0, 1, 2, 3, 4, 5, 6, 7])

## Concatenating, Stacking
Stacking will create a new dimension (axis), while concatenating does not.

In [10]:
# concatenating
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[11, 12], [13, 14]])

np.concatenate([arr1, arr2], axis=0)
np.r_[arr1, arr2]  # same

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [11]:
np.concatenate([arr1, arr2], axis=1) 
np.c_[arr1, arr2]  # same

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [12]:
# stacking
np.stack([arr1, arr2], axis=2)  # `arr1`, `arr2` must have the same shape

array([[[ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14]]])

* stacking arrays $A^i$ along axis 0 gives the array $B[i,j,k] = A^i[j,k]$.
* stacking arrays $A^i$ along axis 1 gives the array $B[i,j,k] = A^j[i,k]$.

In [34]:
# column_stack(): build an matrix by stacking given columns and/or matrices
a = np.array([0, 10, 20])  # a 1-D array 
b = np.array([1, 11, 21])

np.column_stack((a, b))  # a & b will be the columns

array([[ 0,  1],
       [10, 11],
       [20, 21]])

In [18]:
c = np.array([[102,103], [112,113], [122,123]])
np.column_stack((a, b, c))  # matrix c will be stacked as-is

array([[  0,   1, 102, 103],
       [ 10,  11, 112, 113],
       [ 20,  21, 122, 123]])

## Splitting

In [29]:
# splitting
arr3 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarrays = np.split(arr3, [1, 2], axis=0)
for arr in subarrays:
    print(arr)
    print('----')

[[1 2]]
----
[[3 4]]
----
[[5 6]
 [7 8]]
----


## Add New Axis with Size 1

In [25]:
arr = np.ones((2,2,3))
arr0 = np.zeros((2, 3))
arr2 = arr0[:, np.newaxis, :]
arr2.shape

(2, 1, 3)

# Advanced ufunc Usage
## ufunc Methods
`reduce(x)`, `accumulate(x)`, `reduceat(x, bins)`, `outer(x, y)`

In [47]:
arr = np.arange(10)
np.add.reduce(arr)  # same as arr.sum()

45

In [48]:
np.add.reduceat(arr, [0,4,7])  # sums of ranges [0:4], [4:7], [7:10]

array([ 6, 15, 24])

In [44]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.add.accumulate(arr, axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [46]:
arr1 = np.array([1, 3, 6])
arr2 = np.array([2, 3])
np.add.outer(arr1, arr2)  # result[i, j] = arr1[i] + arr2[j]

array([[3, 4],
       [5, 6],
       [8, 9]])

## Writing New ufunc's

In [55]:
def compare(x, y):
    return 1 if x > y else 0 if x == y else -1

# create ufunc from Python function:
compare_ufunc = np.vectorize(compare, otypes=[np.float64])  

compare_ufunc(np.array([1, 5, 7, 8]), np.array([5, 3, 2, 8]))

array([-1.,  1.,  1.,  0.])

* ufunc's created using `vectorize()` is can be very slow, as they require a Python function call to compute each element.